### basic settings

# site properties and page defaults
title: Computational Social Listening Lab | UPenn
description: Data Science x Health & Psychology
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: /csl-lab

# site social media and other links
links:
  email: sharathg@cis.upenn.edu
  google-scholar: 76_hrfUAAAAJ
  github: chandrasg
  twitter: sharathguntuku

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
    - name: orcid
      input:
        - ../_data/orcid.yaml
    - name: google-scholar
      input:
        - ../_data/google-scholar.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
